"""drop unused columns from despesas_restos_pagar

Revision ID: 5329f4288940
Revises: 5d5fc267eda8
Create Date: 2026-06-28 22:31:28.049611

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5329f4288940"
down_revision: Union[str, Sequence[str], None] = "5d5fc267eda8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("despesas_restos_pagar", "situacao")
    op.drop_column("despesas_restos_pagar", "valor")
    op.drop_column("despesas_restos_pagar", "fornecedor")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("despesas_restos_pagar", sa.Column("fornecedor", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("despesas_restos_pagar", sa.Column("valor", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("despesas_restos_pagar", sa.Column("situacao", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
