"""add missing columns

Revision ID: 5d5fc267eda8
Revises: a47c1f2d4ca9
Create Date: 2026-06-26 17:16:20.832599

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5d5fc267eda8"
down_revision: Union[str, Sequence[str], None] = "a47c1f2d4ca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
