"""add missing columns to despesas_por_exibilidade

Revision ID: 6a2e943b674e
Revises: 5329f4288940
Create Date: 2026-07-06 14:51:14.504829

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a2e943b674e"
down_revision: Union[str, Sequence[str], None] = "5329f4288940"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("despesas_por_exigibilidade", sa.Column("empenho", sa.String(), nullable=False))
    op.add_column("despesas_por_exigibilidade", sa.Column("tipolista", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("codentidade", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("entidade", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("ficha", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("codlo", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("catec", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("fornecedor", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("vadem", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("vapag", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("desco", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("anula", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("pagliq", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("venci", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("dtpag", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("foninduso", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("fongrupo", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("foncodigo", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("vingrupo", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("vincodigo", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("fonro", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("justificativa", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("datajusti", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("justificativa_texto", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("tit_just", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("quebrou", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("fonte_nome", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("unidade_nome", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("contrato", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("contrato_categoria", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("contrato_categoria_descr", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("processoadm", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("proclic", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("numsub", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("dtatesto", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("cgc", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("dtprocesso", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("autorizadordespesa", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("insmf", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("cpf_autorizadordespesa", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("notas", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("nempg", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("anoemp", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("tpem", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("tit_hist", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("produ", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("valor_empenho", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("licit", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("pkemp", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("tipoquebra", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("motivo", sa.String(), nullable=True))
    op.add_column("despesas_por_exigibilidade", sa.Column("ordem_liquidacao", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("despesas_por_exigibilidade", "ordem_liquidacao")
    op.drop_column("despesas_por_exigibilidade", "motivo")
    op.drop_column("despesas_por_exigibilidade", "tipoquebra")
    op.drop_column("despesas_por_exigibilidade", "pkemp")
    op.drop_column("despesas_por_exigibilidade", "licit")
    op.drop_column("despesas_por_exigibilidade", "valor_empenho")
    op.drop_column("despesas_por_exigibilidade", "produ")
    op.drop_column("despesas_por_exigibilidade", "tit_hist")
    op.drop_column("despesas_por_exigibilidade", "tpem")
    op.drop_column("despesas_por_exigibilidade", "anoemp")
    op.drop_column("despesas_por_exigibilidade", "nempg")
    op.drop_column("despesas_por_exigibilidade", "notas")
    op.drop_column("despesas_por_exigibilidade", "cpf_autorizadordespesa")
    op.drop_column("despesas_por_exigibilidade", "insmf")
    op.drop_column("despesas_por_exigibilidade", "autorizadordespesa")
    op.drop_column("despesas_por_exigibilidade", "dtprocesso")
    op.drop_column("despesas_por_exigibilidade", "cgc")
    op.drop_column("despesas_por_exigibilidade", "dtatesto")
    op.drop_column("despesas_por_exigibilidade", "numsub")
    op.drop_column("despesas_por_exigibilidade", "proclic")
    op.drop_column("despesas_por_exigibilidade", "processoadm")
    op.drop_column("despesas_por_exigibilidade", "contrato_categoria_descr")
    op.drop_column("despesas_por_exigibilidade", "contrato_categoria")
    op.drop_column("despesas_por_exigibilidade", "contrato")
    op.drop_column("despesas_por_exigibilidade", "unidade_nome")
    op.drop_column("despesas_por_exigibilidade", "fonte_nome")
    op.drop_column("despesas_por_exigibilidade", "quebrou")
    op.drop_column("despesas_por_exigibilidade", "tit_just")
    op.drop_column("despesas_por_exigibilidade", "justificativa_texto")
    op.drop_column("despesas_por_exigibilidade", "datajusti")
    op.drop_column("despesas_por_exigibilidade", "justificativa")
    op.drop_column("despesas_por_exigibilidade", "fonro")
    op.drop_column("despesas_por_exigibilidade", "vincodigo")
    op.drop_column("despesas_por_exigibilidade", "vingrupo")
    op.drop_column("despesas_por_exigibilidade", "foncodigo")
    op.drop_column("despesas_por_exigibilidade", "fongrupo")
    op.drop_column("despesas_por_exigibilidade", "foninduso")
    op.drop_column("despesas_por_exigibilidade", "dtpag")
    op.drop_column("despesas_por_exigibilidade", "venci")
    op.drop_column("despesas_por_exigibilidade", "pagliq")
    op.drop_column("despesas_por_exigibilidade", "anula")
    op.drop_column("despesas_por_exigibilidade", "desco")
    op.drop_column("despesas_por_exigibilidade", "vapag")
    op.drop_column("despesas_por_exigibilidade", "vadem")
    op.drop_column("despesas_por_exigibilidade", "fornecedor")
    op.drop_column("despesas_por_exigibilidade", "catec")
    op.drop_column("despesas_por_exigibilidade", "codlo")
    op.drop_column("despesas_por_exigibilidade", "ficha")
    op.drop_column("despesas_por_exigibilidade", "entidade")
    op.drop_column("despesas_por_exigibilidade", "codentidade")
    op.drop_column("despesas_por_exigibilidade", "tipolista")
    op.drop_column("despesas_por_exigibilidade", "empenho")
    # ### end Alembic commands ###
