"""initial migration

Revision ID: c5cee52135be
Revises:
Create Date: 2026-06-26 16:50:21.437072

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5cee52135be"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contratos",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("numero", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fornecedor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("objeto", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_inicio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_fim", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("licitacao_numero", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("modali", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valcon", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("empenhado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "numero"),
    )
    op.create_table(
        "despesas_extra_orcamentaria",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("numero", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fornecedor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "numero"),
    )
    op.create_table(
        "despesas_gerais",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("numero", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fornecedor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("empenhado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("liquidado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pago", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_empenho", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("orgao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("datae", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nomefor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nomeempresa", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("produ", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "numero"),
    )
    op.create_table(
        "despesas_por_exigibilidade",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tipo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("valor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "tipo"),
    )
    op.create_table(
        "despesas_por_fornecedor",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("empenhado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("liquidado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pago", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("insmf", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cepci", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "codigo"),
    )
    op.create_table(
        "despesas_por_orgao",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("empenhado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("liquidado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pago", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dotac", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("altdo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dotacao_atualizada", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "codigo"),
    )
    op.create_table(
        "despesas_por_unidade",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("empenhado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("liquidado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pago", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dotac", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("altdo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dotacao_atualizada", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "codigo"),
    )
    op.create_table(
        "despesas_restos_pagar",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("numero", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fornecedor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("situacao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pago", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "numero"),
    )
    op.create_table(
        "diarias",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("numero", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("beneficiario", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("destino", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("favorecido", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cargo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("unidade", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "numero"),
    )
    op.create_table(
        "emendas_cad",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("numero", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("numero_emenda", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resumo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valor_total", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("empenhado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("autor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tipo_emenda_descr", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("esfera_origem", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ato_normativo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("destinacao_descr", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "numero"),
    )
    op.create_table(
        "emendas_impositivas",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("numero", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "numero"),
    )
    op.create_table(
        "empresas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "licitacoes",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("numero", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("modalidade", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("objeto", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("situacao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_abertura", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("carona", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("discr", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "numero"),
    )
    op.create_table(
        "metadata",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "pessoal",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("matricula", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cargo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("remuneracao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("proventos", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "mes", "matricula"),
    )
    op.create_table(
        "receita_detalhes",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("previsto", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("arrecadado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "codigo"),
    )
    op.create_table(
        "receita_estado",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("previsto", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("arrecadado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("previsao_atualizada", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("arrecadado_total", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "codigo"),
    )
    op.create_table(
        "receita_extra_orcamentaria",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "codigo"),
    )
    op.create_table(
        "receita_orcamentaria",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("previsto", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("arrecadado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("previsao_atualizada", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("arrecadado_total", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "codigo"),
    )
    op.create_table(
        "receita_uniao",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("previsto", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("arrecadado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("previsao_atualizada", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("arrecadado_total", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "codigo"),
    )
    op.create_table(
        "transferencias",
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("empresa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codigo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("entidade_pagadora", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("entidade_recebedora", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("repasse", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("devolucao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ano", "empresa", "codigo"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transferencias")
    op.drop_table("receita_uniao")
    op.drop_table("receita_orcamentaria")
    op.drop_table("receita_extra_orcamentaria")
    op.drop_table("receita_estado")
    op.drop_table("receita_detalhes")
    op.drop_table("pessoal")
    op.drop_table("metadata")
    op.drop_table("licitacoes")
    op.drop_table("empresas")
    op.drop_table("emendas_impositivas")
    op.drop_table("emendas_cad")
    op.drop_table("diarias")
    op.drop_table("despesas_restos_pagar")
    op.drop_table("despesas_por_unidade")
    op.drop_table("despesas_por_orgao")
    op.drop_table("despesas_por_fornecedor")
    op.drop_table("despesas_por_exigibilidade")
    op.drop_table("despesas_gerais")
    op.drop_table("despesas_extra_orcamentaria")
    op.drop_table("contratos")
    # ### end Alembic commands ###
