name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */10 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app
        env:
          APP_URL: ${{ vars.APP_URL }}
        run: |
          curl -f $APP_URL || exit 0
